#!/bin/bash

# Demonstração do Sistema de Vesting

echo "=== DEMONSTRAÇÃO DO SISTEMA DE VESTING LAUNCHPAD LUNES ==="
echo ""
echo "O sistema de vesting foi implementado com sucesso!"
echo ""
echo "📦 MÓDULOS IMPLEMENTADOS:"
echo "   1. vesting_system.rs - Sistema base de vesting"
echo "   2. integrated_launchpad.rs - Launchpad com vesting integrado"
echo ""
echo "🔧 FUNCIONALIDADES:"
echo "   ✅ Configuração de vesting por fase"
echo "   ✅ Liberação inicial configurável (TGE)"
echo "   ✅ Cliff period (período de espera)"
echo "   ✅ Liberação linear após cliff"
echo "   ✅ Cálculo automático de tokens disponíveis"
echo "   ✅ Sistema de claim para saques"
echo ""
echo "📊 EXEMPLO DE CONFIGURAÇÃO POR FASE:"
echo ""
echo "WHITELIST (Early Investors):"
echo "   • Liberação inicial: 10%"
echo "   • Cliff: 30 dias"
echo "   • Vesting total: 365 dias"
echo "   • Proteção máxima contra dump"
echo ""
echo "PRE-SALE:"
echo "   • Liberação inicial: 20%"
echo "   • Cliff: 0 dias"
echo "   • Vesting total: 180 dias"
echo "   • Balanço entre liquidez e proteção"
echo ""
echo "PUBLIC SALE:"
echo "   • Liberação inicial: 30%"
echo "   • Cliff: 0 dias"
echo "   • Vesting total: 90 dias"
echo "   • Maior liquidez para investidores"
echo ""
echo "📈 SIMULAÇÃO DE VESTING (10,000 tokens, Whitelist):"
echo ""
echo "Dia 0 (Compra):"
echo "   → 1,000 tokens liberados (10% TGE)"
echo "   → 9,000 tokens bloqueados"
echo ""
echo "Dia 30 (Fim do Cliff):"
echo "   → Início da liberação linear"
echo "   → ~27 tokens/dia liberados"
echo ""
echo "Dia 180 (6 meses):"
echo "   → ~4,500 tokens liberados (45%)"
echo "   → 5,500 tokens bloqueados"
echo ""
echo "Dia 365 (1 ano):"
echo "   → 10,000 tokens liberados (100%)"
echo "   → Vesting completo!"
echo ""
echo "🔒 SEGURANÇA:"
echo "   • Vesting imutável após criação"
echo "   • Cálculos on-chain transparentes"
echo "   • Proteção contra manipulação de blocos"
echo "   • Eventos auditáveis para todos os claims"
echo ""
echo "💡 USO PRÁTICO:"
echo ""
echo "1. Investidor compra na fase Whitelist:"
echo "   participate_with_vesting(project_id, PhaseType::Whitelist)"
echo ""
echo "2. Verificar tokens disponíveis:"
echo "   get_claimable_amount(user, project_id, phase_type)"
echo ""
echo "3. Sacar tokens liberados:"
echo "   claim_vested_tokens(project_id, phase_type)"
echo ""
echo "=== SISTEMA DE VESTING PRONTO PARA PRODUÇÃO! ===

