[package]
name = "launchpad" # Renomeando para algo mais simples
version = "2.0.0"
authors = ["Lunes Launchpad Team"]
edition = "2021"
description = "Core logic for the Lunes Launchpad platform."
license = "MIT"
repository = "https://github.com/lunes-launchpad/launchpad"

[dependencies]
ink = { version = "5.1.1", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }

[dev-dependencies]
ink_e2e = { version = "5.1.1" }

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
e2e-tests = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
